name: Auto commit

on:
  workflow_dispatch:

jobs:
  auto_commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          date '+%Y-%m-%dT%H:%M:%SZ' > LAST_UPDATED
          git config --local user.email "fakhri@student.unp.ac.id"
          git config --local user.name "fakhriaditiarahman"
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore(bot): auto commit"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.CLASSIC_TOKEN }}
